#' Recover Bootstrap Weights
#'
#' @description `fwb.array()` returns the bootstrap weights generated by [fwb()].
#'
#' @inheritParams fwb.ci
#'
#' @returns
#' A matrix with `R` rows and `n` columns, where `R` is the number of bootstrap replications and `n` is the number of observations in `boot.out$data`.
#'
#' @details
#' `fwb()` records what is needed to reproduce the weights it drew, and `fwb.array()` reads that record: the saved `seed` when `simple = FALSE`, or the random number stream reserved for each replicate when `simple = TRUE`. Either way the weights are recovered in the calling session, so nothing needs to be set up beforehand and the result does not depend on how the original call was parallelized or on whether `statistic` drew random numbers of its own. The state of the random number generator is left unchanged.
#'
#' Bootstrap weights are used in computing BCa confidence intervals by approximating the empirical influence function for each unit with respect to each parameter (see Examples).
#'
#' @seealso
#' * [fwb()] for performing the fractional weighted bootstrap
#' * \pkgfun{boot}{boot.array} for the equivalent function in \pkg{boot}
#'
#' See `vignette("fwb-rep")` for information on replicability.
#'
#'
#' @examples
#' set.seed(123)
#' data("infert")
#'
#' fit_fun <- function(data, w) {
#'   fit <- glm(case ~ spontaneous + induced, data = data,
#'              family = "quasibinomial", weights = w)
#'   coef(fit)
#' }
#'
#' fwb_out <- fwb(infert, fit_fun, R = 300,
#'                verbose = FALSE)
#'
#' fwb_weights <- fwb.array(fwb_out)
#'
#' dim(fwb_weights)
#'
#' # Recover computed estimates:
#' est1 <- fit_fun(infert, fwb_weights[1, ])
#'
#' stopifnot(all.equal(est1, fwb_out$t[1, ]))
#'
#' # Compute empirical influence function:
#' empinf <- lm.fit(x = fwb_weights / ncol(fwb_weights),
#'                  y = fwb_out$t)$coefficients
#'
#' empinf <- sweep(empinf, 2L, colMeans(empinf))

#' @export
fwb.array <- function(fwb.out) {
  arg::arg_supplied(fwb.out)
  arg::arg_is(fwb.out, "boot")

  if (identical(.attr(fwb.out, "boot_type"), "boot")) {
    rlang::check_installed("boot")
    return(boot::boot.array(fwb.out))
  }

  arg::arg_is(fwb.out, "fwb")

  gen_weights <- make_gen_weights(fwb.out[["wtype"]])

  n <- nrow(fwb.out[["data"]])
  R <- fwb.out[["R"]]

  cluster <- fwb.out[["cluster"]]
  strata <- fwb.out[["strata"]]

  if (is_not_null(strata)) {
    strata <- factor(strata)
  }

  #One weight is drawn per cluster and then spread over its members, so the generator
  #works at cluster scale and the result is expanded to unit scale at the end. With
  #both present, `fwb()` collapses `strata` to one entry per cluster, which has to be
  #reproduced here or the generator would be handed the wrong number of columns.
  if (is_null(cluster)) {
    n_w <- n
    expand <- NULL
  }
  else {
    cluster <- factor(cluster)
    n_w <- nlevels(cluster)
    expand <- as.integer(cluster)

    if (is_not_null(strata)) {
      cs <- unique(data.frame(cluster, strata))
      strata <- factor(cs[[2L]])
    }
  }

  w <- {
    #An exhaustive multinomial run drew no random numbers, so the weights come back by
    #re-running the enumeration rather than from any recorded seed.
    if (isTRUE(.attr(fwb.out, "exhaustive")))
      gen_all_multinom_weights(n_w, strata)
    else if (isTRUE(.attr(fwb.out, "simple")))
      replay_stream_weights(gen_weights, .attr(fwb.out, "seeds"),
                            n_w, R, strata)
    else
      with_seed_preserved(gen_weights(n_w, R, strata),
                          new_seed = .attr(fwb.out, "seeds"))
  }

  if (is_null(expand)) {
    return(w)
  }

  w[, expand, drop = FALSE]
}

#Re-draw `simple = TRUE` weights one replicate at a time from the recorded streams.
#
#Because each replicate's stream was recorded rather than inferred, this needs no
#knowledge of how the original run was parallelized and gives the same answer whatever
#`statistic` did to the random number stream.
replay_stream_weights <- function(gen_weights, seeds, n, R, strata) {
  if (is_null(seeds)) {
    arg::err("the bootstrap weights cannot be recovered from an {.cls fwb} object created by {.pkg fwb} before version 0.7.0; re-run {.fun fwb} to compute this quantity")
  }

  w <- matrix(0, nrow = R, ncol = n)

  with_seed_preserved({
    for (i in seq_len(R)) {
      set_stream_seed(seeds[i, ])
      w[i, ] <- drop(gen_weights(n, 1L, strata))
    }
  })

  w
}
